/**
 * Curated cross-cap NSE universe (~150 symbols) covering large-cap, mid-cap,
 * small-cap, penny stocks and ETFs. Used to seed the `stocks` table on boot
 * so the AI Discovery scanner has a meaningful pool to analyse without needing
 * to fetch the full ~5,000-symbol NSE master file at startup.
 *
 * Rows are [symbol, name, sector, market_cap_tier].
 *  - large   : top-100 by mcap (Nifty100-ish)
 *  - mid     : Nifty Midcap-150
 *  - small   : Nifty Smallcap
 *  - micro   : ~₹1000-3000cr mcap
 *  - penny   : sub-₹50 stocks with reasonable volume
 *  - etf     : index ETFs
 */
export interface SeedStock {
  symbol: string;
  name: string;
  sector: string;
  tier: 'large' | 'mid' | 'small' | 'micro' | 'penny' | 'etf' | 'index';
}

export const SEED_STOCKS: SeedStock[] = [
  // ── LARGE-CAP ─────────────────────────────────────────────
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', tier: 'large' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT', tier: 'large' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT', tier: 'large' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking', tier: 'large' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking', tier: 'large' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', tier: 'large' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking', tier: 'large' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking', tier: 'large' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Financials', tier: 'large' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Financials', tier: 'large' },
  { symbol: 'ITC', name: 'ITC Limited', sector: 'FMCG', tier: 'large' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG', tier: 'large' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG', tier: 'large' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG', tier: 'large' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Construction', tier: 'large' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom', tier: 'large' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer', tier: 'large' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Auto', tier: 'large' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Auto', tier: 'large' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Auto', tier: 'large' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Auto', tier: 'large' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Auto', tier: 'large' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Auto', tier: 'large' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT', tier: 'large' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT', tier: 'large' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT', tier: 'large' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma', tier: 'large' },
  { symbol: 'DRREDDY', name: "Dr Reddy's Laboratories", sector: 'Pharma', tier: 'large' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma', tier: 'large' },
  { symbol: 'DIVISLAB', name: "Divi's Laboratories", sector: 'Pharma', tier: 'large' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Power', tier: 'large' },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Power', tier: 'large' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy', tier: 'large' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining', tier: 'large' },
  { symbol: 'IOC', name: 'Indian Oil Corp', sector: 'Energy', tier: 'large' },
  { symbol: 'BPCL', name: 'BPCL', sector: 'Energy', tier: 'large' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals', tier: 'large' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals', tier: 'large' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals', tier: 'large' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement', tier: 'large' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Cement', tier: 'large' },
  { symbol: 'SHREECEM', name: 'Shree Cement', sector: 'Cement', tier: 'large' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate', tier: 'large' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports & SEZ', sector: 'Logistics', tier: 'large' },
  { symbol: 'ADANIGREEN', name: 'Adani Green Energy', sector: 'Power', tier: 'large' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer', tier: 'large' },
  { symbol: 'DMART', name: 'Avenue Supermarts', sector: 'Retail', tier: 'large' },
  { symbol: 'NAUKRI', name: 'Info Edge', sector: 'Internet', tier: 'large' },
  { symbol: 'LICI', name: 'LIC of India', sector: 'Insurance', tier: 'large' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance', tier: 'large' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance', tier: 'large' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking', tier: 'large' },

  // ── MID-CAP ───────────────────────────────────────────────
  { symbol: 'TVSMOTOR', name: 'TVS Motor', sector: 'Auto', tier: 'mid' },
  { symbol: 'ASHOKLEY', name: 'Ashok Leyland', sector: 'Auto', tier: 'mid' },
  { symbol: 'BOSCHLTD', name: 'Bosch India', sector: 'Auto', tier: 'mid' },
  { symbol: 'PIDILITIND', name: 'Pidilite Industries', sector: 'Chemicals', tier: 'mid' },
  { symbol: 'COLPAL', name: 'Colgate Palmolive', sector: 'FMCG', tier: 'mid' },
  { symbol: 'DABUR', name: 'Dabur India', sector: 'FMCG', tier: 'mid' },
  { symbol: 'GODREJCP', name: 'Godrej Consumer', sector: 'FMCG', tier: 'mid' },
  { symbol: 'MARICO', name: 'Marico', sector: 'FMCG', tier: 'mid' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG', tier: 'mid' },
  { symbol: 'VBL', name: 'Varun Beverages', sector: 'FMCG', tier: 'mid' },
  { symbol: 'AUROPHARMA', name: 'Aurobindo Pharma', sector: 'Pharma', tier: 'mid' },
  { symbol: 'LUPIN', name: 'Lupin', sector: 'Pharma', tier: 'mid' },
  { symbol: 'TORNTPHARM', name: 'Torrent Pharma', sector: 'Pharma', tier: 'mid' },
  { symbol: 'BIOCON', name: 'Biocon', sector: 'Biotech', tier: 'mid' },
  { symbol: 'PERSISTENT', name: 'Persistent Systems', sector: 'IT', tier: 'mid' },
  { symbol: 'COFORGE', name: 'Coforge', sector: 'IT', tier: 'mid' },
  { symbol: 'MPHASIS', name: 'Mphasis', sector: 'IT', tier: 'mid' },
  { symbol: 'LTIM', name: 'LTIMindtree', sector: 'IT', tier: 'mid' },
  { symbol: 'LTTS', name: 'L&T Technology Services', sector: 'IT', tier: 'mid' },
  { symbol: 'PAGEIND', name: 'Page Industries', sector: 'Consumer', tier: 'mid' },
  { symbol: 'TRENT', name: 'Trent', sector: 'Retail', tier: 'mid' },
  { symbol: 'BERGEPAINT', name: 'Berger Paints', sector: 'Consumer', tier: 'mid' },
  { symbol: 'INDIGO', name: 'InterGlobe Aviation', sector: 'Aviation', tier: 'mid' },
  { symbol: 'CONCOR', name: 'Container Corp', sector: 'Logistics', tier: 'mid' },
  { symbol: 'SAIL', name: 'Steel Authority of India', sector: 'Metals', tier: 'mid' },
  { symbol: 'NMDC', name: 'NMDC', sector: 'Mining', tier: 'mid' },
  { symbol: 'VEDL', name: 'Vedanta', sector: 'Metals', tier: 'mid' },
  { symbol: 'JINDALSTEL', name: 'Jindal Steel & Power', sector: 'Metals', tier: 'mid' },
  { symbol: 'IRCTC', name: 'IRCTC', sector: 'Tourism', tier: 'mid' },
  { symbol: 'IRFC', name: 'Indian Railway Finance', sector: 'Financials', tier: 'mid' },
  { symbol: 'RECLTD', name: 'REC Limited', sector: 'Financials', tier: 'mid' },
  { symbol: 'PFC', name: 'Power Finance Corp', sector: 'Financials', tier: 'mid' },
  { symbol: 'BANKBARODA', name: 'Bank of Baroda', sector: 'Banking', tier: 'mid' },
  { symbol: 'CANBK', name: 'Canara Bank', sector: 'Banking', tier: 'mid' },
  { symbol: 'PNB', name: 'Punjab National Bank', sector: 'Banking', tier: 'mid' },
  { symbol: 'IDFCFIRSTB', name: 'IDFC First Bank', sector: 'Banking', tier: 'mid' },
  { symbol: 'FEDERALBNK', name: 'Federal Bank', sector: 'Banking', tier: 'mid' },
  { symbol: 'CHOLAFIN', name: 'Cholamandalam Finance', sector: 'Financials', tier: 'mid' },
  { symbol: 'MUTHOOTFIN', name: 'Muthoot Finance', sector: 'Financials', tier: 'mid' },
  { symbol: 'LICHSGFIN', name: 'LIC Housing Finance', sector: 'Financials', tier: 'mid' },
  { symbol: 'PAYTM', name: 'One 97 Communications', sector: 'Fintech', tier: 'mid' },
  { symbol: 'ZOMATO', name: 'Zomato (Eternal)', sector: 'Internet', tier: 'mid' },
  { symbol: 'POLICYBZR', name: 'PB Fintech', sector: 'Fintech', tier: 'mid' },
  { symbol: 'NYKAA', name: 'FSN E-Commerce', sector: 'Internet', tier: 'mid' },
  { symbol: 'DELHIVERY', name: 'Delhivery', sector: 'Logistics', tier: 'mid' },
  { symbol: 'TATAPOWER', name: 'Tata Power', sector: 'Power', tier: 'mid' },
  { symbol: 'NHPC', name: 'NHPC', sector: 'Power', tier: 'mid' },
  { symbol: 'GAIL', name: 'GAIL India', sector: 'Energy', tier: 'mid' },
  { symbol: 'PETRONET', name: 'Petronet LNG', sector: 'Energy', tier: 'mid' },
  { symbol: 'HINDPETRO', name: 'HPCL', sector: 'Energy', tier: 'mid' },

  // ── SMALL-CAP ─────────────────────────────────────────────
  { symbol: 'PRESTIGE', name: 'Prestige Estates', sector: 'Realty', tier: 'small' },
  { symbol: 'GODREJPROP', name: 'Godrej Properties', sector: 'Realty', tier: 'small' },
  { symbol: 'OBEROIRLTY', name: 'Oberoi Realty', sector: 'Realty', tier: 'small' },
  { symbol: 'DLF', name: 'DLF', sector: 'Realty', tier: 'small' },
  { symbol: 'BHARATFORG', name: 'Bharat Forge', sector: 'Auto', tier: 'small' },
  { symbol: 'EXIDEIND', name: 'Exide Industries', sector: 'Auto', tier: 'small' },
  { symbol: 'AMARAJABAT', name: 'Amara Raja Energy', sector: 'Auto', tier: 'small' },
  { symbol: 'CUMMINSIND', name: 'Cummins India', sector: 'Industrials', tier: 'small' },
  { symbol: 'ABB', name: 'ABB India', sector: 'Industrials', tier: 'small' },
  { symbol: 'SIEMENS', name: 'Siemens', sector: 'Industrials', tier: 'small' },
  { symbol: 'BEL', name: 'Bharat Electronics', sector: 'Defence', tier: 'small' },
  { symbol: 'HAL', name: 'Hindustan Aeronautics', sector: 'Defence', tier: 'small' },
  { symbol: 'BEML', name: 'BEML', sector: 'Defence', tier: 'small' },
  { symbol: 'MAZDOCK', name: 'Mazagon Dock', sector: 'Defence', tier: 'small' },
  { symbol: 'COCHINSHIP', name: 'Cochin Shipyard', sector: 'Defence', tier: 'small' },
  { symbol: 'IDEA', name: 'Vodafone Idea', sector: 'Telecom', tier: 'small' },
  { symbol: 'INDHOTEL', name: 'Indian Hotels', sector: 'Hospitality', tier: 'small' },
  { symbol: 'JUBLFOOD', name: 'Jubilant FoodWorks', sector: 'Hospitality', tier: 'small' },
  { symbol: 'CROMPTON', name: 'Crompton Greaves', sector: 'Consumer', tier: 'small' },
  { symbol: 'WHIRLPOOL', name: 'Whirlpool India', sector: 'Consumer', tier: 'small' },
  { symbol: 'VOLTAS', name: 'Voltas', sector: 'Consumer', tier: 'small' },
  { symbol: 'HAVELLS', name: 'Havells India', sector: 'Consumer', tier: 'small' },
  { symbol: 'POLYCAB', name: 'Polycab India', sector: 'Industrials', tier: 'small' },
  { symbol: 'KEI', name: 'KEI Industries', sector: 'Industrials', tier: 'small' },
  { symbol: 'APLAPOLLO', name: 'APL Apollo Tubes', sector: 'Metals', tier: 'small' },
  { symbol: 'IEX', name: 'Indian Energy Exchange', sector: 'Power', tier: 'small' },
  { symbol: 'CDSL', name: 'CDSL', sector: 'Financials', tier: 'small' },
  { symbol: 'BSE', name: 'BSE Limited', sector: 'Financials', tier: 'small' },
  { symbol: 'MCX', name: 'MCX India', sector: 'Financials', tier: 'small' },
  { symbol: 'KPITTECH', name: 'KPIT Technologies', sector: 'IT', tier: 'small' },
  { symbol: 'TATAELXSI', name: 'Tata Elxsi', sector: 'IT', tier: 'small' },
  { symbol: 'CYIENT', name: 'Cyient', sector: 'IT', tier: 'small' },

  // ── MICRO-CAP ─────────────────────────────────────────────
  { symbol: 'RAILTEL', name: 'RailTel Corp', sector: 'Telecom', tier: 'micro' },
  { symbol: 'IRCON', name: 'Ircon International', sector: 'Construction', tier: 'micro' },
  { symbol: 'RVNL', name: 'Rail Vikas Nigam', sector: 'Construction', tier: 'micro' },
  { symbol: 'HUDCO', name: 'Housing & Urban Dev Corp', sector: 'Financials', tier: 'micro' },
  { symbol: 'NBCC', name: 'NBCC India', sector: 'Construction', tier: 'micro' },
  { symbol: 'ENGINERSIN', name: 'Engineers India', sector: 'Industrials', tier: 'micro' },
  { symbol: 'MAHLIFE', name: 'Mahindra Lifespace', sector: 'Realty', tier: 'micro' },
  { symbol: 'CESC', name: 'CESC', sector: 'Power', tier: 'micro' },
  { symbol: 'JSWENERGY', name: 'JSW Energy', sector: 'Power', tier: 'micro' },
  { symbol: 'TORNTPOWER', name: 'Torrent Power', sector: 'Power', tier: 'micro' },
  { symbol: 'CGPOWER', name: 'CG Power & Industrial', sector: 'Industrials', tier: 'micro' },
  { symbol: 'CAPLIPOINT', name: 'Caplin Point', sector: 'Pharma', tier: 'micro' },
  { symbol: 'GRANULES', name: 'Granules India', sector: 'Pharma', tier: 'micro' },
  { symbol: 'NATCOPHARM', name: 'Natco Pharma', sector: 'Pharma', tier: 'micro' },

  // ── PENNY (sub-₹50, liquid) ───────────────────────────────
  { symbol: 'YESBANK', name: 'Yes Bank', sector: 'Banking', tier: 'penny' },
  { symbol: 'SUZLON', name: 'Suzlon Energy', sector: 'Power', tier: 'penny' },
  { symbol: 'JPPOWER', name: 'Jaiprakash Power Ventures', sector: 'Power', tier: 'penny' },
  { symbol: 'IFCI', name: 'IFCI', sector: 'Financials', tier: 'penny' },
  { symbol: 'IRB', name: 'IRB Infrastructure', sector: 'Construction', tier: 'penny' },
  { symbol: 'GMRINFRA', name: 'GMR Airports Infra', sector: 'Construction', tier: 'penny' },
  { symbol: 'RPOWER', name: 'Reliance Power', sector: 'Power', tier: 'penny' },
  { symbol: 'TRIDENT', name: 'Trident', sector: 'Textiles', tier: 'penny' },
  { symbol: 'TATATELE', name: 'Tata Teleservices', sector: 'Telecom', tier: 'penny' },
  { symbol: 'SOUTHBANK', name: 'South Indian Bank', sector: 'Banking', tier: 'penny' },
  { symbol: 'PNBHOUSING', name: 'PNB Housing Finance', sector: 'Financials', tier: 'penny' },

  // ── ETFs ──────────────────────────────────────────────────
  { symbol: 'NIFTYBEES', name: 'Nippon Nifty 50 ETF', sector: 'ETF', tier: 'etf' },
  { symbol: 'GOLDBEES', name: 'Nippon Gold ETF', sector: 'ETF', tier: 'etf' },
  { symbol: 'BANKBEES', name: 'Nippon Bank ETF', sector: 'ETF', tier: 'etf' },
  { symbol: 'CPSEETF', name: 'CPSE ETF', sector: 'ETF', tier: 'etf' },
  { symbol: 'JUNIORBEES', name: 'Nippon Nifty Next 50 ETF', sector: 'ETF', tier: 'etf' },
  { symbol: 'ITBEES', name: 'Nippon IT ETF', sector: 'ETF', tier: 'etf' },

  // ── INDEX ─────────────────────────────────────────────────
  { symbol: 'NIFTY50', name: 'NIFTY 50 Index', sector: 'Index', tier: 'index' },
];
